In [2]:
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=2)
pprint = pp.pprint

In [3]:
def create_state(n):
    state = np.zeros((2**n, 1))
    state[0,:] = 1
    return state

# Define common quantum logic gates (single qubit operators)
I = np.eye(2)
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0, -1j], [1j, 0]])
Z = np.array([[1, 0], [0, -1]])
H = 1/np.sqrt(2) * np.array([[1, 1],[1, -1]])

def create_controlled_gate(n, control, target, U):
    pass

# Controlled NOT (CNOT) Gate
CNOT = np.zeros((4,4))
CNOT[0:2,0:2] = I
CNOT[2:4,2:4] = X

### 2-qubit quantum circuit examples

In [5]:
# Create Bell State
xi = create_state(2)  # Create 2-qubit state |00>

# First, create the H (tensor) I gate
G0 = np.kron(H, I)

# Then, create the CNOT_01 gate
G1 = CNOT

# Multiply by CNOT gate
xf = G1 @ G0 @ xi
print(xf)  # Gives correct expected output 1/sqrt(2) (|00> + |11>)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


### 3-qubit quantum circuit examples

In [12]:
# The exact circuit as above with a third qubit added on

G0 = np.kron(np.kron(H, I), I)
G1 = np.kron(CNOT, I)
xi = create_state(3)

# Construct the circuit
U = G1 @ G0
xf = U @ xi
print(xf)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.70710678]
 [0.        ]]


In [16]:
gates = np.array([G0, G1])

def create_circuit(gates):
    """Construct the quantum circuit from an array of unitary gates."""
    U = gates[0]

    for i in range(1, gates.shape[0]):
        U = gates[i] @ U
    return U

U = create_circuit(gates)
pprint(U)

array([[ 0.70710678,  0.        ,  0.        ,  0.        ,  0.70710678,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.        ,  0.        ,
         0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.        ,  0.        ,
         0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.70710678,  0.        ,
         0.        ,  0.        ,  0.70710678],
       [ 0.        ,  0.        ,  0.70710678,  0.        ,  0.        ,
         0.        , -0.70710678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.70710678,  0.        ,
         0.        ,  0.        , -0.70710678],
       [ 0.70710678,  0.        ,  0.        ,  0.        , -0.70710678,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.        ,  0.        ,
        -0.70710678,  0.        ,  0.        ]])


In [ ]:
xi = create_state(2)  # Create 2-qubit state |00>

# First, create the H (tensor) I gate
G0 = np.kron(H, I)

# Multiply by CNOT gate
xf = CNOT @ G0 @ x
print(xf)  # Gives correct expected output 1/sqrt(2) (|00> + |11>)

In [85]:
# Matrix multiplication methods
x = 1/np.sqrt(2) * np.array([[1,1]]).reshape(2,1)  # |+> state
H @ x
np.tensordot(H, x, axes=1)

array([[1.00000000e+00],
       [2.23711432e-17]])

In [87]:
# Try to create CNOT via tensor products
state0 = np.array([[1, 0]]).T  # Ket
state1 = np.array([[0, 1]])    # Bra

print(np.tensordot(state0.conj().T, state0, axes=0).reshape(2,2))  # Must be reshaped :/
print(np.outer(state1, state1))  # This is more readable.
print(state0.conj().T)
print(np.kron(state0.conj().T, state0))  # Actually works as expected!
print(np.kron(state1.conj().T, state1))

[[1 0]
 [0 0]]
[[0 0]
 [0 1]]
[[1 0]]
[[1 0]
 [0 0]]
[[0 0]
 [0 1]]
